// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const pageFooter: string;
export const noticeContainer: string;
export const localeListContainer: string;
